## Интро 

Введение в библиотеки pandas, numpy.  

`Никогда не делаем так:`
```python
from pandas import *
```

`А делаем вот так:`

In [2]:
import pandas as pd
import numpy as np

### Чтение
`read_csv()` -- читаем из **.csv**-файла  
`head()`     -- смотрим первые 5 записей  
`tail()`     -- смотрим последние 5 записей

In [3]:
df = pd.read_csv('datasets/titanic.csv', sep=',')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# смотрим форму датафрейма

print(type(df))
df.shape

<class 'pandas.core.frame.DataFrame'>


(891, 12)

### Предобработка
`drop_duplicates()` -- удаляет дубликаты.  
`isna()`     -- проверяет записи на пустые и значения NaN (not a number).  
`filna(value)`     -- заменяет все пустые значения и значения NaN на value.  
`replace( object )`     -- заменяет значения по правилу из object.

In [5]:
df.drop_duplicates()

# можно выбрать конкретные столбцы по которым хотим удалить дубликаты
df.drop_duplicates(subset=['Sex','Age'])

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
819          820         0       3   
829          830         1       1   
843          844         0       3   
851          852         0       3   
879          880         1       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
819                       Skoog, Master. Karl Thorsten    male  10.0      3   
829          Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
843                         Lemberopolous, Mr. Peter L    male  34.5      0   
851                                Svensson, Mr. Johan    male  74.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
819      2            347088  27.9000   NaN        S  
829      0            113572  80.0000   B28      NaN  
843      0              2683   6.4375   NaN        C  
851      0            347060   7.7750   NaN        S  
879      1             11767  83.1583   C50        C  

[147 rows x 12 columns]

#### ВАЖНО! 
Большинство функций Pandas не работают inplace!  
Чтобы сохранить результаты предобработки -- применяем результат переменной либо указываем аргумент `inplace=True` там где это возможно.

In [6]:
df.drop_duplicates(subset=['Sex','Age'])
df.shape

(891, 12)

In [7]:
### V1

df_new = df.drop_duplicates(subset=['Sex','Age'])
df_new.shape

(147, 12)

In [8]:
### V2

df_drop = df.copy()
df_drop.drop_duplicates(subset=['Sex','Age'], inplace=True)
df_drop.shape

(147, 12)

In [9]:
df = df.drop_duplicates()
df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [10]:
df = df.fillna(0)
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00     0        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   0.0      1      2  W./C. 6607  23.45     0        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75     0        Q

In [11]:
### замена значений по правилу
rule = {'male': 0, 'female': 1}
df['Sex'] = df['Sex'].replace(rule)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500     0        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250     0        S  
3            113803  53.1000  C123        S  
4            373450   8.0500     0        S

### Фильтрация и индексация
Правило следующие:  
`df[ df[column] &condition &value ]`

In [12]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
a[a > 10]

array([11, 12, 13, 14, 15])

In [14]:
df[df['Sex'] == 1]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1   
..                                                 ...  ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)    1  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika    1  22.0      0   
885               Rice, Mrs. William (Margaret Norton)    1  39.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1   0.0      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250     0        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333     0        S  
9        0            237736  30.0708     0        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000     0        S  
882      0              7552  10.5167     0        S  
885      5            382652  29.1250     0        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500     0        S  

[314 rows x 12 columns]

In [15]:
df[df['Fare'] > 300]

PassengerId  Survived  Pclass                                Name  Sex  \
258          259         1       1                    Ward, Miss. Anna    1   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez    0   
737          738         1       1              Lesurer, Mr. Gustave J    0   

      Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  35.0      0      0  PC 17755  512.3292            0        C  
679  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737  35.0      0      0  PC 17755  512.3292         B101        C

In [16]:
### фильтрация по нескольким полям

df[ (df['Fare'] > 200) & (df['Age'] < 40) & (df['Sex'] == 0)]

PassengerId  Survived  Pclass                                Name  Sex  \
27            28         0       1      Fortune, Mr. Charles Alexander    0   
118          119         0       1            Baxter, Mr. Quigg Edmond    0   
377          378         0       1           Widener, Mr. Harry Elkins    0   
527          528         0       1                  Farthing, Mr. John    0   
557          558         0       1                 Robbins, Mr. Victor    0   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez    0   
737          738         1       1              Lesurer, Mr. Gustave J    0   

      Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
27   19.0      3      2     19950  263.0000  C23 C25 C27        S  
118  24.0      0      1  PC 17558  247.5208      B58 B60        C  
377  27.0      0      2    113503  211.5000          C82        C  
527   0.0      0      0  PC 17483  221.7792          C95        S  
557   0.0      0      0  PC 17757  227.5250            0        C  
679  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737  35.0      0      0  PC 17755  512.3292         B101        C

In [17]:
### для текстовых данных, фильтрация по совпадению текста

df[df['Name'].str.contains('Mr. O')]

PassengerId  Survived  Pclass                     Name  Sex   Age  SibSp  \
0              1         0       3  Braund, Mr. Owen Harris    0  22.0      1   
60            61         0       3    Sirayanian, Mr. Orsen    0  22.0      0   
138          139         0       3      Osen, Mr. Olaf Elon    0  16.0      0   
154          155         0       3    Olsen, Mr. Ole Martin    0   0.0      0   
499          500         0       3       Svensson, Mr. Olof    0  24.0      0   
804          805         1       3  Hedman, Mr. Oskar Arvid    0  27.0      0   
834          835         0       3   Allum, Mr. Owen George    0  18.0      0   

     Parch     Ticket    Fare Cabin Embarked  
0        0  A/5 21171  7.2500     0        S  
60       0       2669  7.2292     0        C  
138      0       7534  9.2167     0        S  
154      0  Fa 265302  7.3125     0        S  
499      0     350035  7.7958     0        S  
804      0     347089  6.9750     0        S  
834      0       2223  8.3000     0        S

In [18]:
### фильтрация по нескольким полям
cols = ['Pclass', 'Name', 'Sex']
df[cols].head()

Pclass                                               Name  Sex
0       3                            Braund, Mr. Owen Harris    0
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1
2       3                             Heikkinen, Miss. Laina    1
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1
4       3                           Allen, Mr. William Henry    0

In [19]:
### индексация, учитывая порядок индексов

df.iloc[15:20, 2:7]

Pclass                                               Name  Sex   Age  \
15       2                   Hewlett, Mrs. (Mary D Kingcome)     1  55.0   
16       3                               Rice, Master. Eugene    0   2.0   
17       2                       Williams, Mr. Charles Eugene    0   0.0   
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0   
19       3                            Masselmani, Mrs. Fatima    1   0.0   

    SibSp  
15      0  
16      4  
17      0  
18      1  
19      0

### Статистики

In [20]:
df['Age'].value_counts()

0.00     177
24.00     30
22.00     27
18.00     26
28.00     25
        ... 
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: Age, Length: 89, dtype: int64

In [21]:
df['Age'].max()

80.0

In [22]:
df['Fare'].mean()

32.2042079685746

In [23]:
### ...и другие итересные агрегатные функции

df['Fare'].sum()

28693.9493

А ещё можно считать корреляции между столбцами

In [24]:
np.corrcoef(df['Sex'], df['Survived'])   ### df['Sex']

array([[1.        , 0.54335138],
       [0.54335138, 1.        ]])

### Почему на диагонале 1?